/**
 * Self-hosts woff2 fonts (latin subset only) from Google Fonts and writes
 * src/css/fonts.css. Re-runnable: `npm run fonts`
 *
 * Google serves ONE variable file for a weight range (Inter), so identical
 * payloads are deduped and declared with a `font-weight: min max` range.
 */
import { writeFile, mkdir, readdir, unlink } from 'node:fs/promises';
import { createHash } from 'node:crypto';

const SPEC = 'family=Inter:wght@400;500&family=Poppins:wght@600;700';
const UA = 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120.0 Safari/537.36';
// latin only — English-only site, so no cyrillic / greek / vietnamese / latin-ext
const LATIN = 'U+0000-00FF';

const css = await (await fetch(`https://fonts.googleapis.com/css2?${SPEC}&display=swap`, {
  headers: { 'User-Agent': UA },
})).text();

await mkdir('src/fonts', { recursive: true });
for (const f of await readdir('src/fonts')) await unlink(`src/fonts/${f}`);

const byHash = new Map();

for (const block of css.split('@font-face').slice(1)) {
  const range = block.match(/unicode-range:\s*([^;]+);/)?.[1] ?? '';
  if (!range.includes(LATIN)) continue;

  const family = block.match(/font-family:\s*'([^']+)'/)[1];
  const weight = Number(block.match(/font-weight:\s*(\d+)/)[1]);
  const style = block.match(/font-style:\s*(\w+)/)?.[1] ?? 'normal';
  const url = block.match(/src:\s*url\(([^)]+)\)/)[1];

  const buf = Buffer.from(await (await fetch(url)).arrayBuffer());
  const hash = createHash('md5').update(buf).digest('hex');

  const hit = byHash.get(hash);
  if (hit) {
    hit.weights.push(weight); // same payload = variable font covering both
  } else {
    byHash.set(hash, { family, style, buf, weights: [weight] });
  }
}

const faces = [];
for (const face of byHash.values()) {
  const min = Math.min(...face.weights);
  const max = Math.max(...face.weights);
  const variable = min !== max;
  const file = `${face.family.toLowerCase()}-${variable ? 'var' : min}.woff2`;

  await writeFile(`src/fonts/${file}`, face.buf);
  faces.push({ ...face, file, weight: variable ? `${min} ${max}` : String(min) });
  console.log(`  ${file.padEnd(22)} ${(face.buf.length / 1024).toFixed(1).padStart(5)} KB  weight ${variable ? `${min}-${max} (variable)` : min}`);
}

await writeFile('src/css/fonts.css', `/* Generated by scripts/fetch-fonts.mjs — do not edit by hand. */
${faces.map(f => `@font-face {
  font-family: '${f.family}';
  font-style: ${f.style};
  font-weight: ${f.weight};
  font-display: swap;
  src: url('../fonts/${f.file}') format('woff2');
}`).join('\n\n')}
`);

const total = faces.reduce((n, f) => n + f.buf.length, 0);
console.log(`\n${faces.length} files, ${(total / 1024).toFixed(1)} KB total -> src/css/fonts.css`);
